import "C:\program Files\microsoft platform SDK\Include\vmr9.idl";
import "C:\program Files\microsoft platform SDK\Include\prsht.idl";
import "C:\program Files\microsoft platform SDK\Include\mshtml.idl";
import "c:\program files\microsoft platform sdk\include\dimm.idl";
import "C:\program Files\microsoft platform SDK\Include\mshtmhst.idl";
import "c:\program files\microsoft platform sdk\include\docobj.idl";
import "C:\program Files\microsoft platform SDK\Include\exdisp.idl";
import "C:\program Files\microsoft platform SDK\Include\objsafe.idl";


[ version(1.0), uuid(CBA8D472-6A21-43DF-9D8C-589E853866C4), helpstring("test 1.0 Type Library") ]
library test
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

}

